name: CI

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write

jobs:
  build-test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: "gradle"
      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew
      - name: Spotless check
        run: ./gradlew --no-daemon spotlessCheck
      - name: Build & test with coverage
        run: ./gradlew --no-daemon clean test jacocoTestReport
        env:
          GITHUB_TOKEN: ${{ secrets.RAVEJOY_TEST_TOKEN }}
      - name: Upload JUnit results
        uses: actions/upload-artifact@v4
        with:
          name: junit-results
          path: build/test-results/test
          if-no-files-found: ignore
      - name: Upload JaCoCo report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: build/reports/jacoco/test
          if-no-files-found: ignore
      - name: Generate Allure report
        uses: simple-elf/allure-report-action@v1
        if: always()
        with:
          allure_results: build/allure-results
          allure_report: build/allure-report
      - name: Upload Allure report artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-report
          path: build/allure-report
          if-no-files-found: ignore
      - name: Publish unit test summary
        if: always()
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: build/test-results/test/*.xml
      - name: Add report links to PR summary
        if: always()
        run: |
          echo "### Reports" >> $GITHUB_STEP_SUMMARY
          echo "- JUnit artifacts: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" >> $GITHUB_STEP_SUMMARY
          echo "- Allure nightly (Pages): enable in Settings → Pages" >> $GITHUB_STEP_SUMMARY

  sonar:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: build-test
    permissions:
      contents: read
      pull-requests: read
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: "gradle"
      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew
      - name: Build for Sonar
        run: ./gradlew --no-daemon test jacocoTestReport
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
