name: CI

on:
  pull_request:
    branches: ["main"]
    paths-ignore:
      - "**/*.md"
      - "LICENSE"
      - ".github/ISSUE_TEMPLATE/**"
  push:
    branches: ["main"]
    paths-ignore:
      - "**/*.md"
      - "LICENSE"
      - ".github/ISSUE_TEMPLATE/**"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write

jobs:
  build-test:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: "gradle"

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Spotless check (with retry)
        uses: nick-invision/retry@v3
        with:
          timeout_minutes: 10
          max_attempts: 3
          retry_on: error
          command: ./gradlew --no-daemon spotlessCheck

      - name: Build & test with coverage (with retry)
        env:
          API_URL: https://api.github.com
          TOKEN: ${{ github.token }}
          TEST_USER: ravejoy-test
        uses: nick-invision/retry@v3
        with:
          timeout_minutes: 20
          max_attempts: 3
          retry_on: error
          command: ./gradlew --no-daemon clean test jacocoTestReport

      - name: Upload JUnit results
        uses: actions/upload-artifact@v4
        with:
          name: junit-results
          path: build/test-results/test
          if-no-files-found: ignore

      - name: Upload JaCoCo report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: build/reports/jacoco/test
          if-no-files-found: ignore

      - name: Generate Allure report
        uses: simple-elf/allure-report-action@v1
        if: always()
        with:
          allure_results: build/allure-results
          allure_report: build/allure-report

      - name: Upload Allure report artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-report
          path: build/allure-report
          if-no-files-found: ignore

      - name: Publish unit test summary
        if: always()
        uses: EnricoMi/publish-unit-test-result-action@v2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          files: build/test-results/test/*.xml
          check_run: false

      - name: Add report links to PR summary
        if: always()
        run: |
          echo "### Reports" >> $GITHUB_STEP_SUMMARY
          echo "- Workflow artifacts: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" >> $GITHUB_STEP_SUMMARY
          echo "- Nightly Allure (GitHub Pages): enable Pages in Settings → Pages" >> $GITHUB_STEP_SUMMARY

  sonar:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: build-test
    if: ${{ github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork == false }}
    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: "gradle"

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Build for Sonar (with retry)
        env:
          API_URL: https://api.github.com
          TOKEN: ${{ github.token }}
          TEST_USER: ravejoy-test
        uses: nick-invision/retry@v3
        with:
          timeout_minutes: 15
          max_attempts: 3
          retry_on: error
          command: ./gradlew --no-daemon test jacocoTestReport

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
