name: Nightly

on:
  schedule:
    - cron: "0 1 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  nightly-report:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: "gradle"

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Nightly build & test
        run: ./gradlew --no-daemon clean test jacocoTestReport
        env:
          GITHUB_TOKEN: ${{ secrets.RAVEJOY_TEST_TOKEN }}

      - name: Generate Allure report
        uses: simple-elf/allure-report-action@v1
        with:
          allure_results: build/allure-results
          allure_report: build/allure-report

      - name: Upload Allure report artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report-nightly
          path: build/allure-report

      - name: Upload JUnit results
        uses: actions/upload-artifact@v4
        with:
          name: junit-results-nightly
          path: build/test-results/test

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/allure-report

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
