name: Nightly

on:
  schedule:
    - cron: "0 1 * * *"

jobs:
  nightly-report:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: "gradle"
      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew
      - name: Nightly build & test
        run: ./gradlew --no-daemon clean test
        env:
          GITHUB_TOKEN: ${{ secrets.RAVEJOY_TEST_TOKEN }}
      - name: Generate Allure report
        uses: simple-elf/allure-report-action@v1
        with:
          allure_results: build/allure-results
          allure_report: build/allure-report
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/allure-report
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
